spring:
  # connessione al database
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa e hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: Limited-Drop-E-Commerce

    # OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope:
              - email
              - profile
              - openid
            redirect-uri: "{baseUrl}/login/oauth2/authorization/{registrationId}"
            authorization-grant-type: authorization_code


# Context path

server:
  servlet:
    context-path: /api

# Logging
logging:
  level:
    root: INFO
    objectmethod:
      it:
        limited_drop_ecommerce: DEBUG
kind: Application








